# .github/workflows/update.yml
name: Update dashboard

on:
  schedule:
    - cron: "0 9,21 * * *"
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: write

concurrency:
  group: climate-dashboard
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build dashboard
        run: python build.py

      - name: Commit to gh-pages
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -B gh-pages
          mkdir -p .
          cp -r dist/* ./
          git add -A
          if git diff --staged --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "Update dashboard: $(date -u +'%Y-%m-%d %H:%M UTC')"
          git push -f origin gh-pages
